const initialVocab = [
    { id: 1, word: "implement", phrase: "implement a new system", meaning: "〜を実装する、実行する" },
    { id: 2, word: "revenue", phrase: "increase tax revenue", meaning: "収入、歳入" },
    { id: 3, word: "procedure", phrase: "follow the procedure", meaning: "手順、手続き" },
    { id: 4, word: "accommodate", phrase: "accommodate up to 500 guests", meaning: "〜を収容できる、〜の要望に応える" },
    { id: 5, word: "evaluate", phrase: "evaluate the performance", meaning: "〜を評価する" },
    { id: 6, word: "candidate", phrase: "a strong candidate for the job", meaning: "候補者" },
    { id: 7, word: "propose", phrase: "propose a new marketing strategy", meaning: "〜を提案する" },
    { id: 8, word: "budget", phrase: "within the annual budget", meaning: "予算" },
    { id: 9, word: "negotiate", phrase: "negotiate the terms of the contract", meaning: "交渉する" },
    { id: 10, word: "confirm", phrase: "confirm the reservation", meaning: "〜を確認する" },
    { id: 11, word: "approve", phrase: "approve the request", meaning: "〜を承認する" },
    { id: 12, word: "submit", phrase: "submit a report by Friday", meaning: "〜を提出する" },
    { id: 13, word: "postpone", phrase: "postpone the meeting", meaning: "〜を延期する" },
    { id: 14, word: "assign", phrase: "assign a task to the team", meaning: "〜を割り当てる" },
    { id: 15, word: "revise", phrase: "revise the document", meaning: "〜を修正する、見直す" },
    { id: 16, word: "notify", phrase: "notify the staff of the change", meaning: "〜に通知する" },
    { id: 17, word: "distribute", phrase: "distribute flyers", meaning: "〜を配布する" },
    { id: 18, word: "extend", phrase: "extend the deadline", meaning: "〜を延長する" },
    { id: 19, word: "require", phrase: "require a valid ID", meaning: "〜を要求する、必要とする" },
    { id: 20, word: "indicate", phrase: "indicate a clear preference", meaning: "〜を示す、指摘する" },
    { id: 21, word: "register", phrase: "register for the seminar", meaning: "登録する" },
    { id: 22, word: "review", phrase: "review the proposal", meaning: "〜を見直す、検討する" },
    { id: 23, word: "purchase", phrase: "purchase new equipment", meaning: "〜を購入する" },
    { id: 24, word: "arrange", phrase: "arrange a meeting", meaning: "〜を手配する、配置する" },
    { id: 25, word: "attach", phrase: "attach a file to the email", meaning: "〜を添付する" },
    { id: 26, word: "participate", phrase: "participate in the workshop", meaning: "参加する" },
    { id: 27, word: "resolve", phrase: "resolve the issue quickly", meaning: "〜を解決する" },
    { id: 28, word: "enclose", phrase: "enclose a document", meaning: "〜を同封する" },
    { id: 29, word: "ensure", phrase: "ensure the safety of everyone", meaning: "〜を確実にする、保証する" },
    { id: 30, word: "launch", phrase: "launch a new product", meaning: "〜を発売する、立ち上げる" },
    {id: 31, word: "facility", phrase: "tour the facility", meaning: "施設、設備" },
    { id: 32, word: "maintenance", phrase: "scheduled maintenance", meaning: "保守、メンテナンス" },
    { id: 33, word: "strategy", phrase: "develop a marketing strategy", meaning: "戦略" },
    { id: 34, word: "board", phrase: "the board of directors", meaning: "取締役会、委員会" },
    { id: 35, word: "committee", phrase: "organize a committee", meaning: "委員会" },
    { id: 36, word: "representative", phrase: "a sales representative", meaning: "担当者、代表者" },
    { id: 37, word: "executive", phrase: "chief executive officer", meaning: "役員、重役" },
    { id: 38, word: "agreement", phrase: "reach an agreement", meaning: "合意、契約" },
    { id: 39, word: "contract", phrase: "sign a contract", meaning: "契約（書）" },
    { id: 40, word: "signature", phrase: "require a signature", meaning: "署名、サイン" },
    { id: 41, word: "destination", phrase: "a popular tourist destination", meaning: "目的地、行き先" },
    { id: 42, word: "luggage", phrase: "carry-on luggage", meaning: "手荷物" },
    { id: 43, word: "itinerary", phrase: "a travel itinerary", meaning: "旅程（表）" },
    { id: 44, word: "passenger", phrase: "passengers on the flight", meaning: "乗客" },
    { id: 45, word: "commute", phrase: "commute to work", meaning: "通勤する" },
    { id: 46, word: "vehicle", phrase: "park a vehicle", meaning: "車両、乗り物" },
    { id: 47, word: "transportation", phrase: "public transportation", meaning: "交通機関、輸送" },
    { id: 48, word: "fare", phrase: "pay the bus fare", meaning: "運賃" },
    { id: 49, word: "intersection", phrase: "at the intersection", meaning: "交差点" },
    { id: 50, word: "pedestrian", phrase: "pedestrians crossing the street", meaning: "歩行者" },
    { id: 51, word: "current", phrase: "current employees", meaning: "現在の" },
    { id: 52, word: "previous", phrase: "previous experience", meaning: "以前の" },
    { id: 53, word: "valid", phrase: "a valid passport", meaning: "有効な" },
    { id: 54, word: "available", phrase: "available upon request", meaning: "利用可能な、手に入る" },
    { id: 55, word: "upcoming", phrase: "upcoming events", meaning: "今度の、近づく" },
    { id: 56, word: "recent", phrase: "in recent years", meaning: "最近の" },
    { id: 57, word: "temporary", phrase: "a temporary worker", meaning: "一時的な" },
    { id: 58, word: "permanent", phrase: "a permanent position", meaning: "常設の、永久の" },
    { id: 59, word: "additional", phrase: "additional information", meaning: "追加の" },
    { id: 60, word: "specific", phrase: "specific details", meaning: "具体的な、特定の" },
    { id: 61, word: "exactly", phrase: "exactly the same", meaning: "正確に、ちょうど" },
    { id: 62, word: "currently", phrase: "currently unavailable", meaning: "現在（は）" },
    { id: 63, word: "recently", phrase: "have recently opened", meaning: "最近" },
    { id: 64, word: "immediately", phrase: "respond immediately", meaning: "すぐに、直ちに" },
    { id: 65, word: "highly", phrase: "highly recommended", meaning: "非常に、大いに" },
    { id: 66, word: "slightly", phrase: "slightly different", meaning: "わずかに" },
    { id: 67, word: "approximately", phrase: "approximately 50 people", meaning: "およそ、約" },
    { id: 68, word: "frequently", phrase: "frequently asked questions", meaning: "頻繁に" },
    { id: 69, word: "rarely", phrase: "rarely happen", meaning: "めったに～ない" },
    { id: 70, word: "strictly", phrase: "strictly prohibited", meaning: "厳格に" },
    { id: 71, word: "complain", phrase: "complain about the service", meaning: "苦情を言う" },
    { id: 72, word: "apologize", phrase: "apologize for the delay", meaning: "謝罪する" },
    { id: 73, word: "replace", phrase: "replace the battery", meaning: "〜を交換する、〜の後任になる" },
    { id: 74, word: "refund", phrase: "receive a full refund", meaning: "返金（する）" },
    { id: 75, word: "guarantee", phrase: "guarantee the quality", meaning: "〜を保証する" },
    { id: 76, word: "warranty", phrase: "under warranty", meaning: "保証（書）" },
    { id: 77, word: "defect", phrase: "a manufacturing defect", meaning: "欠陥、不良" },
    { id: 78, word: "malfunction", phrase: "equipment malfunction", meaning: "故障、誤作動" },
    { id: 79, word: "feedback", phrase: "customer feedback", meaning: "フィードバック、意見" },
    { id: 80, word: "survey", phrase: "conduct a survey", meaning: "アンケート調査" },
    { id: 81, word: "invest", phrase: "invest in the stock market", meaning: "投資する" },
    { id: 82, word: "profit", phrase: "make a huge profit", meaning: "利益" },
    { id: 83, word: "expense", phrase: "travel expenses", meaning: "経費、費用" },
    { id: 84, word: "estimate", phrase: "an estimated cost", meaning: "見積もり、見積もる" },
    { id: 85, word: "invoice", phrase: "send an invoice", meaning: "請求書" },
    { id: 86, word: "charge", phrase: "free of charge", meaning: "料金、請求する" },
    { id: 87, word: "discount", phrase: "a 10% discount", meaning: "割引" },
    { id: 88, word: "promotion", phrase: "a sales promotion", meaning: "販売促進、昇進" },
    { id: 89, word: "display", phrase: "display the products", meaning: "展示する" },
    { id: 90, word: "inventory", phrase: "check the inventory", meaning: "在庫（調査）" },
    { id: 91, word: "stock", phrase: "out of stock", meaning: "在庫、株式" },
    { id: 92, word: "supplier", phrase: "a reliable supplier", meaning: "供給業者、納入業者" },
    { id: 93, word: "deliver", phrase: "deliver the package", meaning: "配達する" },
    { id: 94, word: "ship", phrase: "free shipping", meaning: "発送する" },
    { id: 95, word: "handling", phrase: "shipping and handling", meaning: "取り扱い、手数料" },
    { id: 96, word: "track", phrase: "track the order", meaning: "追跡する" },
    { id: 97, word: "receipt", phrase: "keep the receipt", meaning: "領収書" },
    { id: 98, word: "bill", phrase: "pay the bill", meaning: "請求書、勘定" },
    { id: 99, word: "account", phrase: "open a bank account", meaning: "口座、アカウント" },
    { id: 100, word: "balance", phrase: "check the balance", meaning: "残高、バランス" },
    { id: 101, word: "deposit", phrase: "make a deposit", meaning: "預金、頭金" },
    { id: 102, word: "withdraw", phrase: "withdraw money from the bank", meaning: "引き出す" },
    { id: 103, word: "loan", phrase: "apply for a loan", meaning: "ローン、貸付" },
    { id: 104, word: "interest", phrase: "a low interest rate", meaning: "利子、関心" },
    { id: 105, word: "tax", phrase: "pay taxes", meaning: "税金" },
    { id: 106, word: "hire", phrase: "hire new staff", meaning: "雇う" },
    { id: 107, word: "employ", phrase: "employ 50 people", meaning: "雇う" },
    { id: 108, word: "interview", phrase: "a job interview", meaning: "面接" },
    { id: 109, word: "resume", phrase: "submit a resume", meaning: "履歴書" },
    { id: 110, word: "qualification", phrase: "meet the qualifications", meaning: "資格、条件" },
    { id: 111, word: "background", phrase: "educational background", meaning: "経歴、背景" },
    { id: 112, word: "skill", phrase: "excellent communication skills", meaning: "スキル、技能" },
    { id: 113, word: "training", phrase: "a training session", meaning: "研修" },
    { id: 114, word: "orientation", phrase: "new employee orientation", meaning: "オリエンテーション" },
    { id: 115, word: "retire", phrase: "retire from the company", meaning: "退職する" },
    { id: 116, word: "resign", phrase: "resign as president", meaning: "辞任する" },
    { id: 117, word: "promote", phrase: "be promoted to manager", meaning: "昇進させる" },
    { id: 118, word: "salary", phrase: "an annual salary", meaning: "給料" },
    { id: 119, word: "wage", phrase: "minimum wage", meaning: "賃金" },
    { id: 120, word: "benefit", phrase: "employee benefits", meaning: "福利厚生、利益" },
    { id: 121, word: "reward", phrase: "a reward for hard work", meaning: "報酬、報い" },
    { id: 122, word: "assess", phrase: "assess the value", meaning: "評価する、査定する" },
    { id: 123, word: "absent", phrase: "be absent from work", meaning: "欠席して" },
    { id: 124, word: "leave", phrase: "on sick leave", meaning: "休暇、去る" },
    { id: 125, word: "schedule", phrase: "ahead of schedule", meaning: "スケジュール、予定" },
    { id: 126, word: "delay", phrase: "a flight delay", meaning: "遅れ、遅らせる" },
    { id: 127, word: "cancel", phrase: "cancel the reservation", meaning: "キャンセルする" },
    { id: 128, word: "appoint", phrase: "appoint a new manager", meaning: "指名する、任命する" },
    { id: 129, word: "deadline", phrase: "meet the deadline", meaning: "締め切り" },
    { id: 130, word: "urgent", phrase: "an urgent message", meaning: "緊急の" },
    { id: 131, word: "agenda", phrase: "the meeting agenda", meaning: "議題、協議事項" },
    { id: 132, word: "colleague", phrase: "a former colleague", meaning: "同僚" },
    { id: 133, word: "branch", phrase: "a branch office", meaning: "支店" },
    { id: 134, word: "headquarters", phrase: "the corporate headquarters", meaning: "本社" },
    { id: 135, word: "brief", phrase: "a brief meeting", meaning: "短い、簡潔な" },
    { id: 136, word: "gather", phrase: "gather information", meaning: "集める" },
    { id: 137, word: "summary", phrase: "an executive summary", meaning: "要約" },
    { id: 138, word: "update", phrase: "a status update", meaning: "最新情報、更新する" },
    { id: 139, word: "remark", phrase: "opening remarks", meaning: "発言、挨拶" },
    { id: 140, word: "emphasize", phrase: "emphasize the importance", meaning: "強調する" },
    { id: 141, word: "concern", phrase: "express concern", meaning: "懸念、心配" },
    { id: 142, word: "inquire", phrase: "inquire about the product", meaning: "問い合わせる" },
    { id: 143, word: "response", phrase: "a quick response", meaning: "返答" },
    { id: 144, word: "instruction", phrase: "follow the instructions", meaning: "指示、説明書" },
    { id: 145, word: "detail", phrase: "provide details", meaning: "詳細" },
    { id: 146, word: "blank", phrase: "fill in the blanks", meaning: "空白" },
    { id: 147, word: "fold", phrase: "fold the paper", meaning: "折りたたむ" },
    { id: 148, word: "bind", phrase: "a securely bound document", meaning: "閉じる、縛る" },
    { id: 149, word: "stack", phrase: "a stack of papers", meaning: "積み重ね、山" },
    { id: 150, word: "drawer", phrase: "the top desk drawer", meaning: "引き出し" },
    { id: 151, word: "cabinet", phrase: "a filing cabinet", meaning: "キャビネット" },
    { id: 152, word: "adjust", phrase: "adjust the volume", meaning: "調整する" },
    { id: 153, word: "operate", phrase: "operate the machine", meaning: "操作する、運営する" },
    { id: 154, word: "manual", phrase: "a user manual", meaning: "取扱説明書" },
    { id: 155, word: "equip", phrase: "be equipped with A", meaning: "Aを備え付ける" },
    { id: 156, word: "out of order", phrase: "the printer is out of order", meaning: "故障中で" },
    { id: 157, word: "fix", phrase: "fix the computer", meaning: "修理する" },
    { id: 158, word: "preserve", phrase: "preserve the historic building", meaning: "保存する" },
    { id: 159, word: "reserve", phrase: "reserve a table", meaning: "予約する" },
    { id: 160, word: "valid", phrase: "valid for one year", meaning: "有効な" },
    { id: 161, word: "expire", phrase: "my passport will expire", meaning: "期限が切れる" },
    { id: 162, word: "strict", phrase: "strict rules", meaning: "厳しい" },
    { id: 163, word: "prohibit", phrase: "smoking is prohibited", meaning: "禁止する" },
    { id: 164, word: "permit", phrase: "a parking permit", meaning: "許可（証）" },
    { id: 165, word: "aware", phrase: "be aware of the problem", meaning: "気づいて" },
    { id: 166, word: "familiar", phrase: "be familiar with the software", meaning: "精通して" },
    { id: 167, word: "responsible", phrase: "be responsible for the project", meaning: "責任がある" },
    { id: 168, word: "capable", phrase: "capable of doing", meaning: "〜する能力がある" },
    { id: 169, word: "handle", phrase: "handle customer complaints", meaning: "対処する、扱う" },
    { id: 170, word: "cope", phrase: "cope with stress", meaning: "うまく処理する" },
    { id: 171, word: "tackle", phrase: "tackle the problem", meaning: "取り組む" },
    { id: 172, word: "effort", phrase: "make an effort", meaning: "努力" },
    { id: 173, word: "progress", phrase: "make progress", meaning: "進歩、進行" },
    { id: 174, word: "achieve", phrase: "achieve a goal", meaning: "達成する" },
    { id: 175, word: "overcome", phrase: "overcome difficulties", meaning: "克服する" },
    { id: 176, word: "result", phrase: "as a result", meaning: "結果" },
    { id: 177, word: "succeed", phrase: "succeed in business", meaning: "成功する" },
    { id: 178, word: "fail", phrase: "fail to notice", meaning: "失敗する、〜し損なう" },
    { id: 179, word: "complete", phrase: "complete the form", meaning: "完了する、完全な" },
    { id: 180, word: "fulfill", phrase: "fulfill the requirement", meaning: "満たす、果たす" },
    { id: 181, word: "provide", phrase: "provide a service", meaning: "提供する" },
    { id: 182, word: "offer", phrase: "offer a discount", meaning: "申し出る、提供する" },
    { id: 183, word: "serve", phrase: "serve as a manager", meaning: "務める、食事を出す" },
    { id: 184, word: "grant", phrase: "grant permission", meaning: "与える、許可する" },
    { id: 185, word: "allow", phrase: "allow people to enter", meaning: "許可する" },
    { id: 186, word: "refuse", phrase: "refuse an offer", meaning: "拒否する" },
    { id: 187, word: "reject", phrase: "reject a proposal", meaning: "却下する、拒絶する" },
    { id: 188, word: "accept", phrase: "accept an invitation", meaning: "受け入れる" },
    { id: 189, word: "receive", phrase: "receive an award", meaning: "受け取る" },
    { id: 190, word: "obtain", phrase: "obtain information", meaning: "得る、入手する" },
    { id: 191, word: "acquire", phrase: "acquire a company", meaning: "買収する、獲得する" },
    { id: 192, word: "gain", phrase: "gain experience", meaning: "得る、増す" },
    { id: 193, word: "lose", phrase: "lose money", meaning: "失う" },
    { id: 194, word: "recover", phrase: "recover from a cold", meaning: "回復する" },
    { id: 195, word: "reduce", phrase: "reduce costs", meaning: "減らす" },
    { id: 196, word: "decrease", phrase: "decrease in number", meaning: "減少する" },
    { id: 197, word: "increase", phrase: "increase sales", meaning: "増やす、増加" },
    { id: 198, word: "expand", phrase: "expand the business", meaning: "拡大する" },
    { id: 199, word: "extend", phrase: "extend the deadline", meaning: "延長する" },
    { id: 200, word: "broaden", phrase: "broaden your knowledge", meaning: "広げる" },
    { id: 201, word: "participate", phrase: "participate in a seminar", meaning: "参加する" },
    { id: 202, word: "attend", phrase: "attend a meeting", meaning: "出席する" },
    { id: 203, word: "join", phrase: "join a club", meaning: "加わる、参加する" },
    { id: 204, word: "enroll", phrase: "enroll in a course", meaning: "登録する、入会する" },
    { id: 205, word: "register", phrase: "register for an event", meaning: "登録する" },
    { id: 206, word: "sign up", phrase: "sign up for a newsletter", meaning: "申し込む" },
    { id: 207, word: "apply", phrase: "apply for a job", meaning: "応募する、申し込む" },
    { id: 208, word: "submit", phrase: "submit a resume", meaning: "提出する" },
    { id: 209, word: "file", phrase: "file a claim", meaning: "提出する、ファイルに綴じる" },
    { id: 210, word: "hand in", phrase: "hand in a report", meaning: "提出する" },
    { id: 211, word: "publish", phrase: "publish a book", meaning: "出版する、公表する" },
    { id: 212, word: "issue", phrase: "issue a statement", meaning: "発行する、問題" },
    { id: 213, word: "release", phrase: "release a new product", meaning: "発売する、発表する" },
    { id: 214, word: "distribute", phrase: "distribute flyers", meaning: "配布する" },
    { id: 215, word: "circulation", phrase: "a large circulation", meaning: "発行部数、循環" },
    { id: 216, word: "article", phrase: "a newspaper article", meaning: "記事、品物" },
    { id: 217, word: "journal", phrase: "a medical journal", meaning: "専門誌、雑誌" },
    { id: 218, word: "brochure", phrase: "a travel brochure", meaning: "パンフレット" },
    { id: 219, word: "pamphlet", phrase: "hand out pamphlets", meaning: "小冊子" },
    { id: 220, word: "flyer", phrase: "pass out flyers", meaning: "チラシ" },
    { id: 221, word: "bulletin", phrase: "a bulletin board", meaning: "掲示板、会報" },
    { id: 222, word: "notice", phrase: "give advance notice", meaning: "通知、気付く" },
    { id: 223, word: "announce", phrase: "announce the results", meaning: "発表する" },
    { id: 224, word: "declare", phrase: "declare independence", meaning: "宣言する、申告する" },
    { id: 225, word: "mention", phrase: "mention the issue", meaning: "言及する" },
    { id: 226, word: "refer", phrase: "refer to a manual", meaning: "参照する、言及する" },
    { id: 227, word: "quote", phrase: "quote a price", meaning: "見積もる、引用する" },
    { id: 228, word: "state", phrase: "state clearly", meaning: "述べる、状態" },
    { id: 229, word: "describe", phrase: "describe the process", meaning: "描写する、説明する" },
    { id: 230, word: "explain", phrase: "explain the reason", meaning: "説明する" },
    { id: 231, word: "construct", phrase: "construct a building", meaning: "建設する" },
    { id: 232, word: "architecture", phrase: "modern architecture", meaning: "建築（学）" },
    { id: 233, word: "structure", phrase: "a wooden structure", meaning: "構造（物）" },
    { id: 234, word: "renovate", phrase: "renovate a house", meaning: "改装する" },
    { id: 235, word: "restore", phrase: "restore a painting", meaning: "修復する" },
    { id: 236, word: "maintain", phrase: "maintain equipment", meaning: "維持する、保守する" },
    { id: 237, word: "inspect", phrase: "inspect a factory", meaning: "検査する" },
    { id: 238, word: "examine", phrase: "examine a document", meaning: "調査する" },
    { id: 239, word: "investigate", phrase: "investigate the cause", meaning: "調査する" },
    { id: 240, word: "survey", phrase: "conduct a survey", meaning: "調査、見渡す" },
    { id: 241, word: "locate", phrase: "locate the office", meaning: "見つける、位置する" },
    { id: 242, word: "site", phrase: "a construction site", meaning: "現場、敷地" },
    { id: 243, word: "property", phrase: "real estate property", meaning: "不動産、財産" },
    { id: 244, word: "estate", phrase: "a real estate agent", meaning: "不動産" },
    { id: 245, word: "rent", phrase: "rent an apartment", meaning: "借りる、家賃" },
    { id: 246, word: "lease", phrase: "sign a lease", meaning: "賃貸借契約、貸す" },
    { id: 247, word: "tenant", phrase: "a new tenant", meaning: "入居者、借家人" },
    { id: 248, word: "landlord", phrase: "contact the landlord", meaning: "家主、地主" },
    { id: 249, word: "neighbor", phrase: "a friendly neighbor", meaning: "近所の人" },
    { id: 250, word: "community", phrase: "the local community", meaning: "地域社会" },
    { id: 251, word: "commute", phrase: "commute by train", meaning: "通勤する" },
    { id: 252, word: "transfer", phrase: "transfer to a new branch", meaning: "転勤する、乗り換える" },
    { id: 253, word: "relocate", phrase: "relocate the office", meaning: "移転する" },
    { id: 254, word: "depart", phrase: "depart from Tokyo", meaning: "出発する" },
    { id: 255, word: "arrive", phrase: "arrive at the station", meaning: "到着する" },
    { id: 256, word: "board", phrase: "board a flight", meaning: "搭乗する" },
    { id: 257, word: "flight", phrase: "a direct flight", meaning: "便、飛行" },
    { id: 258, word: "route", phrase: "a bus route", meaning: "経路、ルート" },
    { id: 259, word: "delay", phrase: "a delayed train", meaning: "遅らせる、遅れ" },
    { id: 260, word: "postpone", phrase: "postpone a meeting", meaning: "延期する" },
    { id: 261, word: "reschedule", phrase: "reschedule an appointment", meaning: "予定を変更する" },
    { id: 262, word: "appointment", phrase: "a dental appointment", meaning: "約束、予約" },
    { id: 263, word: "reservation", phrase: "make a reservation", meaning: "予約" },
    { id: 264, word: "book", phrase: "book a hotel room", meaning: "予約する" },
    { id: 265, word: "confirm", phrase: "confirm a booking", meaning: "確認する" },
    { id: 266, word: "cancel", phrase: "cancel an order", meaning: "取り消す" },
    { id: 267, word: "fee", phrase: "an admission fee", meaning: "料金、手数料" },
    { id: 268, word: "fare", phrase: "a train fare", meaning: "運賃" },
    { id: 269, word: "fine", phrase: "pay a parking fine", meaning: "罰金" },
    { id: 270, word: "toll", phrase: "a toll road", meaning: "通行料" },
    { id: 271, word: "receipt", phrase: "ask for a receipt", meaning: "領収書" },
    { id: 272, word: "refund", phrase: "get a full refund", meaning: "返金" },
    { id: 273, word: "reimburse", phrase: "reimburse travel expenses", meaning: "払い戻す" },
    { id: 274, word: "budget", phrase: "a tight budget", meaning: "予算" },
    { id: 275, word: "fund", phrase: "raise funds", meaning: "資金、基金" },
    { id: 276, word: "grant", phrase: "a research grant", meaning: "助成金、与える" },
    { id: 277, word: "donate", phrase: "donate money to charity", meaning: "寄付する" },
    { id: 278, word: "charity", phrase: "a local charity", meaning: "慈善団体" },
    { id: 279, word: "volunteer", phrase: "volunteer for a project", meaning: "ボランティアをする" },
    { id: 280, word: "contribute", phrase: "contribute to the team", meaning: "貢献する、寄付する" },
    { id: 281, word: "advertise", phrase: "an advertising campaign", meaning: "宣伝する" },
    { id: 282, word: "commercial", phrase: "a television commercial", meaning: "商業の、コマーシャル" },
    { id: 283, word: "campaign", phrase: "launch a campaign", meaning: "キャンペーン" },
    { id: 284, word: "introduce", phrase: "introduce a new system", meaning: "導入する、紹介する" },
    { id: 285, word: "attract", phrase: "attract customers", meaning: "引き付ける" },
    { id: 286, word: "appeal", phrase: "appeal to younger consumers", meaning: "訴えかける、魅力" },
    { id: 287, word: "target", phrase: "target audience", meaning: "標的、対象にする" },
    { id: 288, word: "audience", phrase: "a large audience", meaning: "聴衆、観客" },
    { id: 289, word: "consumer", phrase: "consumer goods", meaning: "消費者" },
    { id: 290, word: "customer", phrase: "a regular customer", meaning: "顧客" },
    { id: 291, word: "client", phrase: "a corporate client", meaning: "クライアント、依頼人" },
    { id: 292, word: "guest", phrase: "welcome a guest", meaning: "ゲスト、客" },
    { id: 293, word: "host", phrase: "host an event", meaning: "主催する、司会者" },
    { id: 294, word: "reception", phrase: "a reception desk", meaning: "受付、歓迎会" },
    { id: 295, word: "banquet", phrase: "a formal banquet", meaning: "宴会、晩餐会" },
    { id: 296, word: "cater", phrase: "cater a party", meaning: "仕出しをする、要求を満たす" },
    { id: 297, word: "beverage", phrase: "food and beverages", meaning: "飲み物" },
    { id: 298, word: "complimentary", phrase: "complimentary breakfast", meaning: "無料の、称賛する" },
    { id: 299, word: "recommend", phrase: "highly recommend", meaning: "勧める" },
    { id: 300, word: "suggest", phrase: "suggest a solution", meaning: "提案する" },
    { id: 301, word: "advice", phrase: "give advice", meaning: "アドバイス" },
    { id: 302, word: "advise", phrase: "advise a client", meaning: "助言する" },
    { id: 303, word: "consult", phrase: "consult an expert", meaning: "相談する" },
    { id: 304, word: "expert", phrase: "a financial expert", meaning: "専門家" },
    { id: 305, word: "professional", phrase: "seek professional help", meaning: "プロの、専門家" },
    { id: 306, word: "specialist", phrase: "an IT specialist", meaning: "専門家" },
    { id: 307, word: "specialize", phrase: "specialize in marketing", meaning: "専門とする" },
    { id: 308, word: "major", phrase: "major in economics", meaning: "専攻する、主要な" },
    { id: 309, word: "minor", phrase: "minor damage", meaning: "軽微な、重要でない" },
    { id: 310, word: "severe", phrase: "severe weather", meaning: "厳しい、深刻な" },
    { id: 311, word: "weather", phrase: "a weather forecast", meaning: "天気" },
    { id: 312, word: "climate", phrase: "a mild climate", meaning: "気候" },
    { id: 313, word: "environment", phrase: "protect the environment", meaning: "環境" },
    { id: 314, word: "pollution", phrase: "reduce air pollution", meaning: "汚染" },
    { id: 315, word: "global", phrase: "the global economy", meaning: "地球規模の、世界的な" },
    { id: 316, word: "international", phrase: "an international flight", meaning: "国際的な" },
    { id: 317, word: "domestic", phrase: "domestic flights", meaning: "国内の" },
    { id: 318, word: "local", phrase: "local residents", meaning: "地元の" },
    { id: 319, word: "resident", phrase: "local residents", meaning: "住民" },
    { id: 320, word: "citizen", phrase: "a senior citizen", meaning: "市民" },
    { id: 321, word: "public", phrase: "public transportation", meaning: "公共の" },
    { id: 322, word: "private", phrase: "a private room", meaning: "私用の、民間の" },
    { id: 323, word: "official", phrase: "an official document", meaning: "公式の" },
    { id: 324, word: "formal", phrase: "a formal suit", meaning: "正式な、フォーマルな" },
    { id: 325, word: "casual", phrase: "casual clothes", meaning: "カジュアルな、何気ない" },
    { id: 326, word: "comfortable", phrase: "a comfortable chair", meaning: "快適な" },
    { id: 327, word: "convenient", phrase: "a convenient location", meaning: "便利な" },
    { id: 328, word: "affordable", phrase: "at an affordable price", meaning: "手頃な" },
    { id: 329, word: "reasonable", phrase: "reasonable prices", meaning: "妥当な、手頃な" },
    { id: 330, word: "expensive", phrase: "too expensive", meaning: "高価な" },
    { id: 331, word: "valuable", phrase: "a valuable asset", meaning: "価値のある" },
    { id: 332, word: "worth", phrase: "well worth the cost", meaning: "価値がある" },
    { id: 333, word: "earn", phrase: "earn a degree", meaning: "稼ぐ、得る" },
    { id: 334, word: "owe", phrase: "owe money", meaning: "借りている" },
    { id: 335, word: "afford", phrase: "cannot afford to buy", meaning: "〜する余裕がある" },
    { id: 336, word: "accurate", phrase: "accurate information", meaning: "正確な" },
    { id: 337, word: "precise", phrase: "precise measurements", meaning: "精密な" },
    { id: 338, word: "exact", phrase: "the exact date", meaning: "正確な" },
    { id: 339, word: "predict", phrase: "predict the future", meaning: "予測する" },
    { id: 340, word: "forecast", phrase: "a sales forecast", meaning: "予測（する）" },
    { id: 341, word: "measure", phrase: "take measures", meaning: "対策を講じる、測る" },
    { id: 342, word: "weigh", phrase: "weigh the luggage", meaning: "重さを量る" },
    { id: 343, word: "compare", phrase: "compare prices", meaning: "比較する" },
    { id: 344, word: "contrast", phrase: "in contrast to", meaning: "対照（的に）" },
    { id: 345, word: "similar", phrase: "similar to the original", meaning: "似ている" },
    { id: 346, word: "identical", phrase: "identical twins", meaning: "全く同じ" },
    { id: 347, word: "different", phrase: "completely different", meaning: "違う" },
    { id: 348, word: "vary", phrase: "prices vary", meaning: "異なる、変わる" },
    { id: 349, word: "various", phrase: "various reasons", meaning: "さまざまな" },
    { id: 350, word: "diverse", phrase: "a diverse workforce", meaning: "多様な" },
    { id: 351, word: "select", phrase: "select an option", meaning: "選ぶ" },
    { id: 352, word: "choose", phrase: "choose a color", meaning: "選ぶ" },
    { id: 353, word: "decide", phrase: "decide to leave", meaning: "決める" },
    { id: 354, word: "determine", phrase: "determine the cause", meaning: "特定する、決定する" },
    { id: 355, word: "conclude", phrase: "conclude a contract", meaning: "結論を下す、終える" },
    { id: 356, word: "finalize", phrase: "finalize the details", meaning: "最終決定する" },
    { id: 357, word: "settle", phrase: "settle a dispute", meaning: "解決する、定住する" },
    { id: 358, word: "solve", phrase: "solve a problem", meaning: "解決する" },
    { id: 359, word: "identify", phrase: "identify the suspect", meaning: "特定する" },
    { id: 360, word: "recognize", phrase: "recognize a face", meaning: "認識する、表彰する" },
    { id: 361, word: "notice", phrase: "notice a change", meaning: "気づく、通知" },
    { id: 362, word: "observe", phrase: "observe the rules", meaning: "観察する、遵守する" },
    { id: 363, word: "rule", phrase: "break a rule", meaning: "規則" },
    { id: 364, word: "regulation", phrase: "safety regulations", meaning: "規制、規則" },
    { id: 365, word: "policy", phrase: "company policy", meaning: "方針、規定" },
    { id: 366, word: "law", phrase: "pass a law", meaning: "法律" },
    { id: 367, word: "legal", phrase: "take legal action", meaning: "合法的な、法的な" },
    { id: 368, word: "illegal", phrase: "illegal parking", meaning: "違法な" },
    { id: 369, word: "standard", phrase: "meet the standard", meaning: "基準" },
    { id: 370, word: "quality", phrase: "high quality", meaning: "品質" },
    { id: 371, word: "quantity", phrase: "a large quantity", meaning: "量" },
    { id: 372, word: "amount", phrase: "a small amount", meaning: "量" },
    { id: 373, word: "volume", phrase: "sales volume", meaning: "量、音量" },
    { id: 374, word: "capacity", phrase: "seating capacity", meaning: "収容能力" },
    { id: 375, word: "limit", phrase: "a speed limit", meaning: "制限" },
    { id: 376, word: "restrict", phrase: "restrict access", meaning: "制限する" },
    { id: 377, word: "ban", phrase: "ban smoking", meaning: "禁止する" },
    { id: 378, word: "avoid", phrase: "avoid traffic jams", meaning: "避ける" },
    { id: 379, word: "prevent", phrase: "prevent accidents", meaning: "防ぐ" },
    { id: 380, word: "protect", phrase: "protect data", meaning: "保護する" },
    { id: 481, word: "draft", phrase: "write a rough draft", meaning: "草稿、下書き" },
    { id: 482, word: "revision", phrase: "make a revision", meaning: "修正、改訂" },
    { id: 483, word: "translation", phrase: "a translation of the document", meaning: "翻訳" },
    { id: 484, word: "interpretation", phrase: "data interpretation", meaning: "解釈、通訳" },
    { id: 485, word: "overview", phrase: "give a brief overview", meaning: "概要" },
    { id: 486, word: "abstract", phrase: "read the abstract", meaning: "要約、抽象的な" },
    { id: 487, word: "correspondence", phrase: "business correspondence", meaning: "文通、通信" },
    { id: 488, word: "directory", phrase: "a company directory", meaning: "名簿、電話帳" },
    { id: 489, word: "extension", phrase: "extension 123", meaning: "内線、延長" },
    { id: 490, word: "recipient", phrase: "the intended recipient", meaning: "受取人" },
    { id: 491, word: "sender", phrase: "return to sender", meaning: "差出人" },
    { id: 492, word: "envelope", phrase: "a stamped envelope", meaning: "封筒" },
    { id: 493, word: "postage", phrase: "postage is included", meaning: "郵便料金" },
    { id: 494, word: "parcel", phrase: "deliver a parcel", meaning: "小包" },
    { id: 495, word: "courier", phrase: "send by courier", meaning: "宅配業者、クーリエ" },
    { id: 496, word: "freight", phrase: "freight train", meaning: "貨物" },
    { id: 497, word: "cargo", phrase: "load the cargo", meaning: "積み荷、貨物" },
    { id: 498, word: "transit", phrase: "goods in transit", meaning: "輸送、通過" },
    { id: 499, word: "customs", phrase: "go through customs", meaning: "税関" },
    { id: 500, word: "border", phrase: "cross the border", meaning: "国境、境界" },
    { id: 501, word: "export", phrase: "export goods to Japan", meaning: "輸出する" },
    { id: 502, word: "import", phrase: "import taxes", meaning: "輸入する" },
    { id: 503, word: "overseas", phrase: "overseas markets", meaning: "海外の" },
    { id: 504, word: "abroad", phrase: "travel abroad", meaning: "海外へ" },
    { id: 505, word: "baggage", phrase: "baggage claim", meaning: "手荷物" },
    { id: 506, word: "carousel", phrase: "the baggage carousel", meaning: "回転コンベア" },
    { id: 507, word: "aisle", phrase: "an aisle seat", meaning: "通路" },
    { id: 508, word: "platform", phrase: "platform 3", meaning: "プラットホーム" },
    { id: 509, word: "vessel", phrase: "a cargo vessel", meaning: "船、管" },
    { id: 510, word: "automobile", phrase: "the automobile industry", meaning: "自動車" },
    { id: 511, word: "commuter", phrase: "a commuter train", meaning: "通勤者" },
    { id: 512, word: "traffic", phrase: "heavy traffic", meaning: "交通（量）" },
    { id: 513, word: "congestion", phrase: "traffic congestion", meaning: "渋滞" },
    { id: 514, word: "detour", phrase: "take a detour", meaning: "迂回（する）" },
    { id: 515, word: "crosswalk", phrase: "use the crosswalk", meaning: "横断歩道" },
    { id: 516, word: "pavement", phrase: "walk on the pavement", meaning: "舗装道路、歩道" },
    { id: 517, word: "avenue", phrase: "Fifth Avenue", meaning: "大通り" },
    { id: 518, word: "boulevard", phrase: "a wide boulevard", meaning: "大通り" },
    { id: 519, word: "direction", phrase: "ask for directions", meaning: "方向、指示" },
    { id: 520, word: "location", phrase: "a prime location", meaning: "場所、立地" },
    { id: 521, word: "venue", phrase: "a concert venue", meaning: "会場" },
    { id: 522, word: "premises", phrase: "on the premises", meaning: "敷地、構内" },
    { id: 523, word: "campus", phrase: "a university campus", meaning: "キャンパス" },
    { id: 524, word: "layout", phrase: "the office layout", meaning: "配置、レイアウト" },
    { id: 525, word: "blueprint", phrase: "draw a blueprint", meaning: "見取り図、青写真" },
    { id: 526, word: "demolish", phrase: "demolish the old building", meaning: "取り壊す" },
    { id: 527, word: "foundation", phrase: "lay the foundation", meaning: "基礎、設立" },
    { id: 528, word: "repair", phrase: "under repair", meaning: "修理（する）" },
    { id: 529, word: "remodel", phrase: "remodel the kitchen", meaning: "改装する" },
    { id: 530, word: "plumbing", phrase: "plumbing problems", meaning: "配管" },
    { id: 531, word: "electricity", phrase: "generate electricity", meaning: "電気" },
    { id: 532, word: "utility", phrase: "utility bills", meaning: "公共料金、実用性" },
    { id: 533, word: "heating", phrase: "a heating system", meaning: "暖房" },
    { id: 534, word: "ventilation", phrase: "poor ventilation", meaning: "換気" },
    { id: 535, word: "thermometer", phrase: "read the thermometer", meaning: "温度計" },
    { id: 536, word: "appliance", phrase: "home appliances", meaning: "家電" },
    { id: 537, word: "gadget", phrase: "a useful gadget", meaning: "小道具、気の利いた機械" },
    { id: 538, word: "machinery", phrase: "heavy machinery", meaning: "機械類" },
    { id: 539, word: "hardware", phrase: "a hardware store", meaning: "金物類、ハードウェア" },
    { id: 540, word: "software", phrase: "install software", meaning: "ソフトウェア" },
    { id: 541, word: "network", phrase: "a computer network", meaning: "ネットワーク" },
    { id: 542, word: "database", phrase: "access the database", meaning: "データベース" },
    { id: 543, word: "spreadsheet", phrase: "create a spreadsheet", meaning: "表計算ソフト" },
    { id: 544, word: "monitor", phrase: "monitor the situation", meaning: "監視する、画面" },
    { id: 545, word: "keyboard", phrase: "type on a keyboard", meaning: "キーボード" },
    { id: 546, word: "plug", phrase: "plug it in", meaning: "プラグ（を差し込む）" },
    { id: 547, word: "cord", phrase: "an extension cord", meaning: "コード" },
    { id: 548, word: "wireless", phrase: "a wireless connection", meaning: "無線の" },
    { id: 549, word: "connectivity", phrase: "internet connectivity", meaning: "接続性" },
    { id: 550, word: "access", phrase: "have access to the file", meaning: "アクセス（権）" },
    { id: 551, word: "log in", phrase: "log in to the account", meaning: "ログインする" },
    { id: 552, word: "password", phrase: "enter your password", meaning: "パスワード" },
    { id: 553, word: "verify", phrase: "verify the signature", meaning: "検証する、確認する" },
    { id: 554, word: "authenticate", phrase: "authenticate a document", meaning: "認証する" },
    { id: 555, word: "authorize", phrase: "an authorized dealer", meaning: "権限を与える" },
    { id: 556, word: "deny", phrase: "deny access", meaning: "拒否する、否定する" },
    { id: 557, word: "consent", phrase: "without my consent", meaning: "同意（する）" },
    { id: 558, word: "endorse", phrase: "endorse a product", meaning: "推薦する、承認する" },
    { id: 559, word: "urge", phrase: "urge them to vote", meaning: "強く促す" },
    { id: 560, word: "compel", phrase: "feel compelled to help", meaning: "強いる" },
    { id: 561, word: "obligation", phrase: "a legal obligation", meaning: "義務" },
    { id: 562, word: "duty", phrase: "on duty", meaning: "職務、義務" },
    { id: 563, word: "responsibility", phrase: "take full responsibility", meaning: "責任" },
    { id: 564, word: "task", phrase: "a difficult task", meaning: "任務、仕事" },
    { id: 565, word: "assignment", phrase: "finish the assignment", meaning: "課題、割り当て" },
    { id: 566, word: "shift", phrase: "the night shift", meaning: "シフト、交代制" },
    { id: 567, word: "overtime", phrase: "work overtime", meaning: "残業" },
    { id: 568, word: "flexible", phrase: "flexible working hours", meaning: "柔軟な" },
    { id: 569, word: "part-time", phrase: "a part-time job", meaning: "パートタイムの" },
    { id: 570, word: "full-time", phrase: "a full-time employee", meaning: "常勤の" },
    { id: 571, word: "freelance", phrase: "a freelance writer", meaning: "フリーランスの" },
    { id: 572, word: "entrepreneur", phrase: "a successful entrepreneur", meaning: "起業家" },
    { id: 573, word: "startup", phrase: "a tech startup", meaning: "スタートアップ（企業）" },
    { id: 574, word: "enterprise", phrase: "a large enterprise", meaning: "企業、事業" },
    { id: 575, word: "corporation", phrase: "a multinational corporation", meaning: "法人、株式会社" },
    { id: 576, word: "subsidiary", phrase: "an overseas subsidiary", meaning: "子会社" },
    { id: 577, word: "affiliate", phrase: "an affiliated company", meaning: "提携先、関連会社" },
    { id: 578, word: "merger", phrase: "a merger between two companies", meaning: "合併" },
    { id: 579, word: "acquisition", phrase: "a corporate acquisition", meaning: "買収、獲得" },
    { id: 580, word: "monopoly", phrase: "a monopoly on the market", meaning: "独占" },
    { id: 581, word: "agreement", phrase: "sign a rental agreement", meaning: "合意、契約（書）" },
    { id: 582, word: "contract", phrase: "a binding contract", meaning: "契約（書）" },
    { id: 583, word: "clause", phrase: "a termination clause", meaning: "（契約などの）条項" },
    { id: 584, word: "term", phrase: "terms and conditions", meaning: "条件、期間、用語" },
    { id: 585, word: "condition", phrase: "working conditions", meaning: "条件、状態" },
    { id: 586, word: "provision", phrase: "a provision of the law", meaning: "規定、条項、準備" },
    { id: 587, word: "warranty", phrase: "a one-year warranty", meaning: "保証（期間）" },
    { id: 588, word: "guarantee", phrase: "satisfaction guaranteed", meaning: "保証する" },
    { id: 589, word: "liability", phrase: "product liability", meaning: "法的責任、負債" },
    { id: 590, word: "negligence", phrase: "professional negligence", meaning: "過失、怠慢" },
    { id: 591, word: "compensation", phrase: "worker's compensation", meaning: "補償、報酬" },
    { id: 592, word: "damage", phrase: "claim for damages", meaning: "損害（賠償金）" },
    { id: 593, word: "lawsuit", phrase: "file a lawsuit", meaning: "訴訟" },
    { id: 594, word: "litigation", phrase: "commercial litigation", meaning: "訴訟" },
    { id: 595, word: "court", phrase: "appear in court", meaning: "法廷、裁判所" },
    { id: 596, word: "judge", phrase: "the presiding judge", meaning: "裁判官、判断する" },
    { id: 597, word: "attorney", phrase: "a defense attorney", meaning: "弁護士" },
    { id: 598, word: "counsel", phrase: "legal counsel", meaning: "弁護士（団）、助言" },
    { id: 599, word: "witness", phrase: "an eyewitness", meaning: "証人、目撃する" },
    { id: 600, word: "testify", phrase: "testify in court", meaning: "証言する" },
    { id: 601, word: "evidence", phrase: "insufficient evidence", meaning: "証拠" },
    { id: 602, word: "verdict", phrase: "reach a verdict", meaning: "評決、判定" },
    { id: 603, word: "guilty", phrase: "be found guilty", meaning: "有罪の" },
    { id: 604, word: "innocent", phrase: "innocent people", meaning: "無罪の" },
    { id: 605, word: "violation", phrase: "a traffic violation", meaning: "違反" },
    { id: 606, word: "compliance", phrase: "in compliance with", meaning: "遵守" },
    { id: 607, word: "regulatory", phrase: "regulatory bodies", meaning: "規制の" },
    { id: 608, word: "audit", phrase: "an internal audit", meaning: "会計監査（する）" },
    { id: 609, word: "finance", phrase: "the finance department", meaning: "財政、財務、融資する" },
    { id: 610, word: "capital", phrase: "raise capital", meaning: "資本（金）、主要な" },
    { id: 611, word: "fund", phrase: "a retirement fund", meaning: "資金、基金" },
    { id: 612, word: "budget", phrase: "a limited budget", meaning: "予算" },
    { id: 613, word: "deficit", phrase: "a trade deficit", meaning: "赤字、不足" },
    { id: 614, word: "surplus", phrase: "a budget surplus", meaning: "黒字、余剰" },
    { id: 615, word: "revenue", phrase: "annual revenue", meaning: "（国の）歳入、（企業の）収益" },
    { id: 616, word: "profit", phrase: "net profit", meaning: "利益" },
    { id: 617, word: "loss", phrase: "a financial loss", meaning: "損失" },
    { id: 618, word: "asset", phrase: "valuable assets", meaning: "資産、財産" },
    { id: 619, word: "debt", phrase: "repay a debt", meaning: "借金、負債" },
    { id: 620, word: "loan", phrase: "apply for a loan", meaning: "ローン、融資" },
    { id: 621, word: "mortgage", phrase: "a home mortgage", meaning: "住宅ローン" },
    { id: 622, word: "interest", phrase: "a high interest rate", meaning: "利息、利回り、関心" },
    { id: 623, word: "dividend", phrase: "pay a dividend", meaning: "配当" },
    { id: 624, word: "stock", phrase: "stock market", meaning: "株、在庫" },
    { id: 625, word: "share", phrase: "market share", meaning: "株、分け前" },
    { id: 626, word: "shareholder", phrase: "a major shareholder", meaning: "株主" },
    { id: 627, word: "invest", phrase: "invest in stocks", meaning: "投資する" },
    { id: 628, word: "portfolio", phrase: "an investment portfolio", meaning: "作品集、投資構成" },
    { id: 629, word: "insurance", phrase: "health insurance", meaning: "保険" },
    { id: 630, word: "premium", phrase: "insurance premiums", meaning: "保険料、割増金" },
    { id: 631, word: "policy", phrase: "an insurance policy", meaning: "保険証券、方針" },
    { id: 632, word: "coverage", phrase: "media coverage", meaning: "（保険の）補償範囲、取材" },
    { id: 633, word: "beneficiary", phrase: "a primary beneficiary", meaning: "受取人、受益者" },
    { id: 634, word: "deductible", phrase: "a high deductible", meaning: "免責額、控除できる" },
    { id: 635, word: "reimburse", phrase: "reimburse expenses", meaning: "払い戻す" },
    { id: 636, word: "subsidize", phrase: "subsidize the project", meaning: "補助金を与える" },
    { id: 637, word: "allowance", phrase: "a housing allowance", meaning: "手当、小遣い" },
    { id: 638, word: "pension", phrase: "a state pension", meaning: "年金" },
    { id: 639, word: "retirement", phrase: "early retirement", meaning: "退職、引退" },
    { id: 640, word: "welfare", phrase: "social welfare", meaning: "福利厚生、福祉" },
    { id: 641, word: "medical", phrase: "a medical checkup", meaning: "医療の" },
    { id: 642, word: "physical", phrase: "a physical examination", meaning: "身体の、物理的な" },
    { id: 643, word: "symptom", phrase: "show symptoms", meaning: "症状" },
    { id: 644, word: "diagnosis", phrase: "a correct diagnosis", meaning: "診断" },
    { id: 645, word: "treatment", phrase: "receive treatment", meaning: "治療、取り扱い" },
    { id: 646, word: "therapy", phrase: "occupational therapy", meaning: "療法" },
    { id: 647, word: "prescription", phrase: "a doctor's prescription", meaning: "処方箋" },
    { id: 648, word: "pharmacy", phrase: "the local pharmacy", meaning: "薬局" },
    { id: 649, word: "clinic", phrase: "a dental clinic", meaning: "診療所、クリニック" },
    { id: 650, word: "physician", phrase: "a family physician", meaning: "医師、内科医" },
    { id: 651, word: "surgeon", phrase: "a skilled surgeon", meaning: "外科医" },
    { id: 652, word: "patient", phrase: "a hospital patient", meaning: "患者、忍耐強い" },
    { id: 653, word: "surgery", phrase: "undergo surgery", meaning: "手術" },
    { id: 654, word: "operation", phrase: "a surgical operation", meaning: "手術、操作、運営" },
    { id: 655, word: "recovery", phrase: "a speedy recovery", meaning: "回復" },
    { id: 656, word: "preventive", phrase: "preventive measures", meaning: "予防の" },
    { id: 657, word: "vaccination", phrase: "get a vaccination", meaning: "予防接種" },
    { id: 658, word: "epidemic", phrase: "a flu epidemic", meaning: "流行、伝染病" },
    { id: 659, word: "hygiene", phrase: "personal hygiene", meaning: "衛生" },
    { id: 660, word: "sanitary", phrase: "sanitary conditions", meaning: "衛生的な" },
    { id: 661, word: "nutrition", phrase: "poor nutrition", meaning: "栄養" },
    { id: 662, word: "diet", phrase: "a balanced diet", meaning: "食事、ダイエット" },
    { id: 663, word: "obesity", phrase: "childhood obesity", meaning: "肥満" },
    { id: 664, word: "fatigue", phrase: "muscle fatigue", meaning: "疲労" },
    { id: 665, word: "stress", phrase: "reduce stress", meaning: "ストレス、強調する" },
    { id: 666, word: "exercise", phrase: "regular exercise", meaning: "運動、練習問題" },
    { id: 667, word: "fitness", phrase: "a fitness center", meaning: "健康、フィットネス" },
    { id: 668, word: "wellness", phrase: "workplace wellness", meaning: "健康" },
    { id: 669, word: "leisure", phrase: "leisure activities", meaning: "余暇、レジャー" },
    { id: 670, word: "recreation", phrase: "recreation facilities", meaning: "娯楽、レクリエーション" },
    { id: 671, word: "tourism", phrase: "the tourism industry", meaning: "観光" },
    { id: 672, word: "souvenir", phrase: "buy a souvenir", meaning: "お土産" },
    { id: 673, word: "excursion", phrase: "a day excursion", meaning: "遠足、小旅行" },
    { id: 674, word: "itinerary", phrase: "a detailed itinerary", meaning: "旅程（表）" },
    { id: 675, word: "accommodation", phrase: "hotel accommodations", meaning: "宿泊施設、適応" },
    { id: 676, word: "reservation", phrase: "make a reservation", meaning: "予約" },
    { id: 677, word: "booking", phrase: "confirm a booking", meaning: "予約" },
    { id: 678, word: "cancellation", phrase: "a cancellation fee", meaning: "キャンセル" },
    { id: 679, word: "refund", phrase: "get a full refund", meaning: "払い戻し" },
    { id: 680, word: "departure", phrase: "time of departure", meaning: "出発" },
    { id: 681, word: "strategy", phrase: "a business strategy", meaning: "戦略" },
    { id: 682, word: "objective", phrase: "meet the objective", meaning: "目標、客観的な" },
    { id: 683, word: "goal", phrase: "achieve a goal", meaning: "目標" },
    { id: 684, word: "mission", phrase: "a company mission", meaning: "使命" },
    { id: 685, word: "vision", phrase: "a long-term vision", meaning: "展望、ビジョン" },
    { id: 686, word: "priority", phrase: "a top priority", meaning: "優先事項" },
    { id: 687, word: "deadline", phrase: "meet the deadline", meaning: "締め切り" },
    { id: 688, word: "schedule", phrase: "behind schedule", meaning: "予定（表）" },
    { id: 689, word: "agenda", phrase: "the meeting agenda", meaning: "協議事項、議題" },
    { id: 690, word: "minute", phrase: "take minutes", meaning: "議事録、分" },
    { id: 691, word: "summary", phrase: "an executive summary", meaning: "要約" },
    { id: 692, word: "conclusion", phrase: "draw a conclusion", meaning: "結論" },
    { id: 693, word: "proposal", phrase: "submit a proposal", meaning: "提案" },
    { id: 694, word: "recommendation", phrase: "make a recommendation", meaning: "勧告、推薦" },
    { id: 695, word: "approval", phrase: "get final approval", meaning: "承認" },
    { id: 696, word: "rejection", phrase: "face rejection", meaning: "拒絶、却下" },
    { id: 697, word: "permission", phrase: "written permission", meaning: "許可" },
    { id: 698, word: "ban", phrase: "a ban on exports", meaning: "禁止（令）" },
    { id: 699, word: "limit", phrase: "a time limit", meaning: "制限、限界" },
    { id: 700, word: "range", phrase: "a wide range of products", meaning: "範囲" },
    { id: 701, word: "scope", phrase: "the scope of the project", meaning: "範囲、余地" },
    { id: 702, word: "aspect", phrase: "every aspect of life", meaning: "側面、局面" },
    { id: 703, word: "factor", phrase: "a key factor", meaning: "要因、要素" },
    { id: 704, word: "element", phrase: "a crucial element", meaning: "要素" },
    { id: 705, word: "feature", phrase: "a unique feature", meaning: "特徴、呼び物" },
    { id: 706, word: "characteristic", phrase: "a personal characteristic", meaning: "特徴" },
    { id: 707, word: "attribute", phrase: "a positive attribute", meaning: "属性、〜のせいにする" },
    { id: 708, word: "benefit", phrase: "mutual benefit", meaning: "利益、恩恵" },
    { id: 709, word: "advantage", phrase: "take advantage of", meaning: "利点、優位" },
    { id: 710, word: "disadvantage", phrase: "be at a disadvantage", meaning: "不利、欠点" },
    { id: 711, word: "drawback", phrase: "the main drawback", meaning: "欠点、不利な点" },
    { id: 712, word: "risk", phrase: "take a risk", meaning: "恐れ、リスク" },
    { id: 713, word: "threat", phrase: "pose a threat", meaning: "脅威" },
    { id: 714, word: "opportunity", phrase: "a golden opportunity", meaning: "機会" },
    { id: 715, word: "challenge", phrase: "face a challenge", meaning: "課題、挑戦" },
    { id: 716, word: "obstacle", phrase: "overcome an obstacle", meaning: "障害（物）" },
    { id: 717, word: "barrier", phrase: "a language barrier", meaning: "障壁" },
    { id: 718, word: "conflict", phrase: "resolve a conflict", meaning: "衝突、対立" },
    { id: 719, word: "dispute", phrase: "a labor dispute", meaning: "論争、紛争" },
    { id: 720, word: "crisis", phrase: "an economic crisis", meaning: "危機" },
    { id: 721, word: "emergency", phrase: "in case of emergency", meaning: "緊急事態" },
    { id: 722, word: "incident", phrase: "a minor incident", meaning: "出来事、事件" },
    { id: 723, word: "accident", phrase: "a traffic accident", meaning: "事故、偶然" },
    { id: 724, word: "event", phrase: "a charity event", meaning: "行事、イベント" },
    { id: 725, word: "occasion", phrase: "on this occasion", meaning: "機会、行事" },
    { id: 726, word: "situation", phrase: "a difficult situation", meaning: "状況" },
    { id: 727, word: "circumstance", phrase: "under any circumstances", meaning: "状況、事情" },
    { id: 728, word: "condition", phrase: "living conditions", meaning: "条件、状態" },
    { id: 729, word: "environment", phrase: "work environment", meaning: "環境" },
    { id: 730, word: "atmosphere", phrase: "a friendly atmosphere", meaning: "雰囲気" },
    { id: 731, word: "resource", phrase: "natural resources", meaning: "資源" },
    { id: 732, word: "energy", phrase: "renewable energy", meaning: "エネルギー" },
    { id: 733, word: "power", phrase: "solar power", meaning: "電力、力" },
    { id: 734, word: "fuel", phrase: "fuel consumption", meaning: "燃料" },
    { id: 735, word: "gasoline", phrase: "a gasoline station", meaning: "ガソリン" },
    { id: 736, word: "electricity", phrase: "save electricity", meaning: "電気" },
    { id: 737, word: "water", phrase: "fresh water", meaning: "水" },
    { id: 738, word: "waste", phrase: "industrial waste", meaning: "廃棄物、無駄にする" },
    { id: 739, word: "pollution", phrase: "water pollution", meaning: "汚染" },
    { id: 740, word: "garbage", phrase: "collect garbage", meaning: "ゴミ" },
    { id: 741, word: "recycle", phrase: "recycle plastic bottles", meaning: "再生利用する" },
    { id: 742, word: "reusable", phrase: "reusable bags", meaning: "再利用可能な" },
    { id: 743, word: "sustainable", phrase: "sustainable development", meaning: "持続可能な" },
    { id: 744, word: "ecological", phrase: "ecological balance", meaning: "生態学的な" },
    { id: 745, word: "nature", phrase: "human nature", meaning: "自然、性質" },
    { id: 746, word: "wildlife", phrase: "protect wildlife", meaning: "野生生物" },
    { id: 747, word: "landscape", phrase: "a beautiful landscape", meaning: "風景" },
    { id: 748, word: "scenery", phrase: "mountain scenery", meaning: "景色" },
    { id: 749, word: "view", phrase: "a room with a view", meaning: "眺め、見解" },
    { id: 750, word: "climate", phrase: "climate change", meaning: "気候" },
    { id: 751, word: "weather", phrase: "unpredictable weather", meaning: "天気" },
    { id: 752, word: "storm", phrase: "a severe storm", meaning: "嵐" },
    { id: 753, word: "rain", phrase: "heavy rain", meaning: "雨" },
    { id: 754, word: "snow", phrase: "light snow", meaning: "雪" },
    { id: 755, word: "wind", phrase: "a strong wind", meaning: "風" },
    { id: 756, word: "temperature", phrase: "room temperature", meaning: "温度" },
    { id: 757, word: "degree", phrase: "a university degree", meaning: "度、学位" },
    { id: 758, word: "heat", phrase: "intense heat", meaning: "熱" },
    { id: 759, word: "cold", phrase: "catch a cold", meaning: "寒さ、風邪" },
    { id: 760, word: "humidity", phrase: "high humidity", meaning: "湿度" },
    { id: 761, word: "pressure", phrase: "work under pressure", meaning: "圧力、プレッシャー" },
    { id: 762, word: "force", phrase: "sales force", meaning: "力、軍隊、強いる" },
    { id: 763, word: "impact", phrase: "a positive impact", meaning: "影響、衝撃" },
    { id: 714, word: "effect", phrase: "side effects", meaning: "効果、影響" },
    { id: 765, word: "consequence", phrase: "suffer the consequences", meaning: "結果、成り行き" },
    { id: 766, word: "result", phrase: "as a result", meaning: "結果" },
    { id: 767, word: "outcome", phrase: "the final outcome", meaning: "結果、成果" },
    { id: 768, word: "output", phrase: "increase output", meaning: "生産高、出力" },
    { id: 769, word: "production", phrase: "mass production", meaning: "生産" },
    { id: 770, word: "yield", phrase: "a high yield", meaning: "収穫（量）、利回り、産出する" },
    { id: 771, word: "performance", phrase: "job performance", meaning: "業績、公演" },
    { id: 772, word: "efficiency", phrase: "energy efficiency", meaning: "効率" },
    { id: 773, word: "productivity", phrase: "labor productivity", meaning: "生産性" },
    { id: 774, word: "growth", phrase: "economic growth", meaning: "成長" },
    { id: 775, word: "expansion", phrase: "business expansion", meaning: "拡大" },
    { id: 776, word: "decline", phrase: "a sharp decline", meaning: "減少、衰退、断る" },
    { id: 777, word: "reduction", phrase: "cost reduction", meaning: "削減" },
    { id: 778, word: "stable", phrase: "a stable price", meaning: "安定した" },
    { id: 779, word: "volatile", phrase: "a volatile market", meaning: "変動しやすい" },
    { id: 780, word: "fluctuation", phrase: "price fluctuations", meaning: "変動" },
    { id: 781, word: "significant", phrase: "a significant change", meaning: "重要な、かなりの" },
    { id: 782, word: "substantial", phrase: "a substantial amount", meaning: "かなりの、実体のある" },
    { id: 783, word: "considerable", phrase: "at considerable expense", meaning: "かなりの" },
    { id: 784, word: "slight", phrase: "a slight increase", meaning: "わずかな" },
    { id: 785, word: "marginal", phrase: "marginal improvement", meaning: "わずかな、余白の" },
    { id: 786, word: "rapid", phrase: "rapid growth", meaning: "急速な" },
    { id: 787, word: "gradual", phrase: "gradual change", meaning: "緩やかな、段階的な" },
    { id: 788, word: "steady", phrase: "steady progress", meaning: "着実な、安定した" },
    { id: 789, word: "constant", phrase: "constant pressure", meaning: "絶え間ない、一定の" },
    { id: 790, word: "abrupt", phrase: "an abrupt change", meaning: "突然の" },
    { id: 791, word: "initial", phrase: "initial stage", meaning: "最初の、初期の" },
    { id: 792, word: "final", phrase: "final decision", meaning: "最終的な" },
    { id: 793, word: "ultimate", phrase: "the ultimate goal", meaning: "究極の、最終的な" },
    { id: 794, word: "eventual", phrase: "eventual success", meaning: "最終的な" },
    { id: 795, word: "primary", phrase: "the primary reason", meaning: "第一の、主要な" },
    { id: 796, word: "secondary", phrase: "secondary education", meaning: "第二の、中等教育の" },
    { id: 797, word: "previous", phrase: "the previous year", meaning: "前の" },
    { id: 798, word: "following", phrase: "the following day", meaning: "次の、〜に続く" },
    { id: 799, word: "subsequent", phrase: "subsequent events", meaning: "その後の" },
    { id: 800, word: "concurrent", phrase: "concurrent events", meaning: "同時に起こる" },
    { id: 801, word: "temporary", phrase: "a temporary job", meaning: "一時的な" },
    { id: 802, word: "permanent", phrase: "a permanent position", meaning: "常設の、終身の" },
    { id: 803, word: "brief", phrase: "a brief meeting", meaning: "短い、簡潔な" },
    { id: 804, word: "lengthy", phrase: "a lengthy process", meaning: "長い、冗長な" },
    { id: 805, word: "eternal", phrase: "eternal life", meaning: "永遠の" },
    { id: 806, word: "immediate", phrase: "immediate response", meaning: "即座の、直接の" },
    { id: 807, word: "urgent", phrase: "urgent matter", meaning: "緊急の" },
    { id: 808, word: "prompt", phrase: "prompt delivery", meaning: "迅速な、促す" },
    { id: 809, word: "punctual", phrase: "be punctual for work", meaning: "時間を守る" },
    { id: 810, word: "delayed", phrase: "a delayed flight", meaning: "遅れた" },
    { id: 811, word: "ancient", phrase: "ancient Greece", meaning: "古代の" },
    { id: 812, word: "modern", phrase: "modern technology", meaning: "現代の" },
    { id: 813, word: "current", phrase: "current situation", meaning: "現在の、潮流" },
    { id: 814, word: "contemporary", phrase: "contemporary art", meaning: "同時代の、現代の" },
    { id: 815, word: "future", phrase: "future plans", meaning: "未来の" },
    { id: 816, word: "upcoming", phrase: "upcoming event", meaning: "来たるべき" },
    { id: 817, word: "forthcoming", phrase: "forthcoming book", meaning: "来たるべき、隠さない" },
    { id: 818, word: "past", phrase: "in the past", meaning: "過去の" },
    { id: 819, word: "recent", phrase: "recent developments", meaning: "最近の" },
    { id: 820, word: "annual", phrase: "annual report", meaning: "年一回の" },
    { id: 821, word: "quarterly", phrase: "quarterly earnings", meaning: "四半期ごとの" },
    { id: 822, word: "monthly", phrase: "monthly magazine", meaning: "月一回の" },
    { id: 823, word: "weekly", phrase: "weekly schedule", meaning: "週一回の" },
    { id: 824, word: "daily", phrase: "daily routine", meaning: "日々の" },
    { id: 825, word: "fortnightly", phrase: "a fortnightly meeting", meaning: "2週間ごとの" },
    { id: 826, word: "biennial", phrase: "a biennial conference", meaning: "2年に1度の" },
    { id: 827, word: "century", phrase: "the 21st century", meaning: "世紀" },
    { id: 828, word: "decade", phrase: "over the last decade", meaning: "10年間" },
    { id: 829, word: "era", phrase: "a new era", meaning: "時代" },
    { id: 830, word: "period", phrase: "a period of stability", meaning: "期間、時代" },
    { id: 831, word: "region", phrase: "the local region", meaning: "地域" },
    { id: 832, word: "district", phrase: "the business district", meaning: "地区" },
    { id: 833, word: "territory", phrase: "overseas territory", meaning: "領土、縄張り" },
    { id: 834, word: "continent", phrase: "the African continent", meaning: "大陸" },
    { id: 835, word: "boundary", phrase: "national boundary", meaning: "境界（線）" },
    { id: 836, word: "frontier", phrase: "crossing the frontier", meaning: "国境、辺境、最前線" },
    { id: 837, word: "suburb", phrase: "live in the suburbs", meaning: "郊外" },
    { id: 838, word: "urban", phrase: "urban planning", meaning: "都市の" },
    { id: 839, word: "rural", phrase: "rural areas", meaning: "田舎の" },
    { id: 840, word: "remote", phrase: "a remote village", meaning: "遠く離れた" },
    { id: 841, word: "neighbor", phrase: "a next-door neighbor", meaning: "隣人" },
    { id: 842, word: "community", phrase: "the local community", meaning: "地域社会" },
    { id: 843, word: "society", phrase: "modern society", meaning: "社会" },
    { id: 844, word: "culture", phrase: "corporate culture", meaning: "文化" },
    { id: 845, word: "tradition", phrase: "follow tradition", meaning: "伝統" },
    { id: 846, word: "custom", phrase: "local customs", meaning: "習慣、慣習" },
    { id: 847, word: "habit", phrase: "a bad habit", meaning: "（個人の）習慣" },
    { id: 848, word: "etiquette", phrase: "business etiquette", meaning: "礼儀作法" },
    { id: 849, word: "manner", phrase: "in a professional manner", meaning: "方法、行儀" },
    { id: 850, word: "moral", phrase: "moral values", meaning: "道徳的な" },
    { id: 851, word: "ethics", phrase: "business ethics", meaning: "倫理" },
    { id: 852, word: "principle", phrase: "guiding principle", meaning: "原理、原則" },
    { id: 853, word: "faith", phrase: "have faith in", meaning: "信頼、信仰" },
    { id: 854, word: "religion", phrase: "freedom of religion", meaning: "宗教" },
    { id: 855, word: "belief", phrase: "personal belief", meaning: "信念、信じること" },
    { id: 856, word: "philosophy", phrase: "management philosophy", meaning: "哲学" },
    { id: 857, word: "perspective", phrase: "from a different perspective", meaning: "視点、観点" },
    { id: 858, word: "attitude", phrase: "a positive attitude", meaning: "態度" },
    { id: 859, word: "behavior", phrase: "human behavior", meaning: "振る舞い、行動" },
    { id: 860, word: "conduct", phrase: "professional conduct", meaning: "行為、実施する" },
    { id: 861, word: "reputation", phrase: "a good reputation", meaning: "評判" },
    { id: 862, word: "status", phrase: "social status", meaning: "地位、状況" },
    { id: 863, word: "prestige", phrase: "prestige brand", meaning: "名声、威信" },
    { id: 864, word: "rank", phrase: "rise in rank", meaning: "階級、ランク付けする" },
    { id: 865, word: "position", phrase: "apply for a position", meaning: "職、位置" },
    { id: 866, word: "role", phrase: "play a key role", meaning: "役割" },
    { id: 867, word: "influence", phrase: "have a huge influence", meaning: "影響" },
    { id: 868, word: "power", phrase: "purchasing power", meaning: "力、権力" },
    { id: 869, word: "authority", phrase: "local authority", meaning: "権限、当局" },
    { id: 870, word: "command", phrase: "good command of English", meaning: "指揮、自由自在に操る力" },
    { id: 871, word: "leadership", phrase: "strong leadership", meaning: "指導力" },
    { id: 872, word: "support", phrase: "customer support", meaning: "支持、支援（する）" },
    { id: 873, word: "cooperation", phrase: "in cooperation with", meaning: "協力" },
    { id: 874, word: "collaboration", phrase: "a collaboration between companies", meaning: "共同作業、コラボ" },
    { id: 875, word: "partnership", phrase: "form a partnership", meaning: "提携" },
    { id: 876, word: "alliance", phrase: "a strategic alliance", meaning: "同盟、提携" },
    { id: 877, word: "union", phrase: "a labor union", meaning: "組合、結合" },
    { id: 878, word: "association", phrase: "a trade association", meaning: "協会、関連" },
    { id: 879, word: "committee", phrase: "a steering committee", meaning: "委員会" },
    { id: 880, word: "board", phrase: "the board of directors", meaning: "板、会議、役員会" },
    { id: 881, word: "council", phrase: "the city council", meaning: "会議、地方議会" },
    { id: 882, word: "department", phrase: "sales department", meaning: "部門、課" },
    { id: 883, word: "division", phrase: "the overseas division", meaning: "部門、分割" },
    { id: 884, word: "branch", phrase: "a local branch", meaning: "支店、枝" },
    { id: 885, word: "headquarters", phrase: "visit the headquarters", meaning: "本社、本部" },
    { id: 886, word: "agency", phrase: "an advertising agency", meaning: "代理店、機関" },
    { id: 887, word: "facility", phrase: "sports facilities", meaning: "施設、設備" },
    { id: 888, word: "institute", phrase: "a research institute", meaning: "研究所、協会" },
    { id: 889, word: "foundation", phrase: "a charitable foundation", meaning: "財団、基礎" },
    { id: 890, word: "organization", phrase: "a non-profit organization", meaning: "組織、団体" },
    { id: 891, word: "actually", phrase: "actually, I'm busy", meaning: "実際には" },
    { id: 892, word: "virtually", phrase: "virtually impossible", meaning: "ほとんど、実質的に" },
    { id: 893, word: "eventually", phrase: "eventually succeed", meaning: "結局、ついに" },
    { id: 894, word: "consequently", phrase: "consequently, prices rose", meaning: "その結果として" },
    { id: 895, word: "therefore", phrase: "therefore, we agree", meaning: "したがって" },
    { id: 896, word: "nevertheless", phrase: "nevertheless, we tried", meaning: "それにもかかわらず" },
    { id: 897, word: "moreover", phrase: "moreover, it's cheap", meaning: "さらに、そのうえ" },
    { id: 898, word: "furthermore", phrase: "furthermore, it's fast", meaning: "さらに" },
    { id: 899, word: "otherwise", phrase: "hurry, otherwise you'll miss it", meaning: "さもなければ" },
    { id: 900, word: "likewise", phrase: "likewise, I'm happy", meaning: "同様に" },
    { id: 901, word: "relative", phrase: "relative to last year", meaning: "相対的な、親戚" },
    { id: 902, word: "absolute", phrase: "absolute confidence", meaning: "絶対的な" },
    { id: 903, word: "relevant", phrase: "relevant information", meaning: "関連のある" },
    { id: 904, word: "irrelevant", phrase: "irrelevant details", meaning: "無関係な" },
    { id: 905, word: "essential", phrase: "it is essential that...", meaning: "不可欠な" },
    { id: 906, word: "optional", phrase: "optional extras", meaning: "任意の" },
    { id: 907, word: "compulsory", phrase: "compulsory education", meaning: "義務的な" },
    { id: 908, word: "mandatory", phrase: "mandatory training", meaning: "必須の" },
    { id: 909, word: "voluntary", phrase: "voluntary work", meaning: "自発的な、ボランティアの" },
    { id: 910, word: "spontaneous", phrase: "a spontaneous reaction", meaning: "自発的な、自然に起きる" },
    { id: 911, word: "favorable", phrase: "favorable conditions", meaning: "好意的な、有利な" },
    { id: 912, word: "unfavorable", phrase: "unfavorable reviews", meaning: "批判的な、不利な" },
    { id: 913, word: "positive", phrase: "a positive outlook", meaning: "前向きな、肯定的な" },
    { id: 914, word: "negative", phrase: "negative impact", meaning: "否定的な、マイナスの" },
    { id: 915, word: "optimistic", phrase: "be optimistic about the future", meaning: "楽観的な" },
    { id: 916, word: "pessimistic", phrase: "a pessimistic view", meaning: "悲観的な" },
    { id: 917, word: "enthusiastic", phrase: "be enthusiastic about", meaning: "熱心な" },
    { id: 918, word: "indifferent", phrase: "be indifferent to politics", meaning: "無関心な" },
    { id: 919, word: "skeptical", phrase: "be skeptical of the plan", meaning: "懐疑的な" },
    { id: 920, word: "ambiguous", phrase: "an ambiguous answer", meaning: "あいまいな" },
    { id: 921, word: "vague", phrase: "a vague memory", meaning: "漠然とした" },
    { id: 922, word: "precise", phrase: "precise measurements", meaning: "正確な" },
    { id: 923, word: "accurate", phrase: "an accurate clock", meaning: "正確な" },
    { id: 924, word: "reliable", phrase: "a reliable source", meaning: "信頼できる" },
    { id: 925, word: "consistent", phrase: "consistent performance", meaning: "一貫した" },
    { id: 926, word: "contradictory", phrase: "contradictory statements", meaning: "矛盾した" },
    { id: 927, word: "paradoxical", phrase: "a paradoxical situation", meaning: "逆説的な" },
    { id: 928, word: "coherent", phrase: "a coherent explanation", meaning: "筋の通った" },
    { id: 929, word: "logical", phrase: "a logical conclusion", meaning: "論理的な" },
    { id: 930, word: "rational", phrase: "a rational decision", meaning: "合理的な" },
    { id: 931, word: "emotional", phrase: "an emotional speech", meaning: "感情的な" },
    { id: 932, word: "subjective", phrase: "a subjective opinion", meaning: "主観的な" },
    { id: 933, word: "objective", phrase: "an objective test", meaning: "客観的な、目標" },
    { id: 934, word: "biased", phrase: "be biased toward", meaning: "偏見のある" },
    { id: 935, word: "impartial", phrase: "an impartial judge", meaning: "公平な" },
    { id: 936, word: "neutral", phrase: "a neutral observer", meaning: "中立の" },
    { id: 937, word: "comprehensive", phrase: "a comprehensive study", meaning: "包括的な、広範囲の" },
    { id: 938, word: "extensive", phrase: "extensive knowledge", meaning: "広範囲な" },
    { id: 939, word: "intensive", phrase: "an intensive course", meaning: "集中的な" },
    { id: 940, word: "thorough", phrase: "a thorough investigation", meaning: "徹底的な" },
    { id: 941, word: "detailed", phrase: "a detailed report", meaning: "詳細な" },
    { id: 942, word: "concise", phrase: "a concise summary", meaning: "簡潔な" },
    { id: 943, word: "brief", phrase: "a brief explanation", meaning: "手短な" },
    { id: 944, word: "explicit", phrase: "explicit instructions", meaning: "明白な" },
    { id: 945, word: "implicit", phrase: "an implicit agreement", meaning: "暗黙の" },
    { id: 946, word: "obvious", phrase: "an obvious mistake", meaning: "明らかな" },
    { id: 947, word: "evident", phrase: "it is evident that...", meaning: "明白な" },
    { id: 948, word: "apparent", phrase: "for no apparent reason", meaning: "一見明白な、外見上の" },
    { id: 949, word: "subtle", phrase: "a subtle difference", meaning: "微妙な" },
    { id: 950, word: "abstract", phrase: "abstract art", meaning: "抽象的な" },
    { id: 951, word: "concrete", phrase: "concrete evidence", meaning: "具体的な" },
    { id: 952, word: "vivid", phrase: "a vivid description", meaning: "鮮やかな" },
    { id: 953, word: "diverse", phrase: "diverse backgrounds", meaning: "多様な" },
    { id: 954, word: "uniform", phrase: "uniform quality", meaning: "均一の、制服" },
    { id: 955, word: "unique", phrase: "a unique opportunity", meaning: "唯一の、独特な" },
    { id: 956, word: "rare", phrase: "a rare species", meaning: "珍しい" },
    { id: 957, word: "scarce", phrase: "water is scarce", meaning: "不足している" },
    { id: 958, word: "redundant", phrase: "redundant systems", meaning: "余剰の、解雇された" },
    { id: 959, word: "obsolete", phrase: "obsolete technology", meaning: "廃れた、時代遅れの" },
    { id: 960, word: "innovative", phrase: "innovative design", meaning: "革新的な" },
    { id: 961, word: "conservative", phrase: "a conservative estimate", meaning: "保守的な、控えめな" },
    { id: 962, word: "radical", phrase: "a radical change", meaning: "根本的な、過激な" },
    { id: 963, word: "moderate", phrase: "moderate prices", meaning: "適度な、穏健な" },
    { id: 964, word: "extreme", phrase: "extreme heat", meaning: "極端な" },
    { id: 965, word: "drastic", phrase: "take drastic measures", meaning: "思い切った、徹底的な" },
    { id: 966, word: "severe", phrase: "severe weather", meaning: "厳しい、深刻な" },
    { id: 967, word: "mild", phrase: "mild symptoms", meaning: "軽い、穏やかな" },
    { id: 968, word: "gentle", phrase: "a gentle reminder", meaning: "優しい、穏やかな" },
    { id: 969, word: "rough", phrase: "a rough estimate", meaning: "おおよその、粗い" },
    { id: 970, word: "tough", phrase: "a tough decision", meaning: "困難な、たくましい" },
    { id: 971, word: "resilient", phrase: "a resilient economy", meaning: "回復力のある" },
    { id: 972, word: "vulnerable", phrase: "vulnerable to attack", meaning: "脆弱な、傷つきやすい" },
    { id: 973, word: "susceptible", phrase: "be susceptible to flu", meaning: "影響を受けやすい" },
    { id: 974, word: "immune", phrase: "immune system", meaning: "免疫のある" },
    { id: 975, word: "resistant", phrase: "heat-resistant", meaning: "耐性のある" },
    { id: 976, word: "persistent", phrase: "persistent cough", meaning: "しつこい、持続的な" },
    { id: 977, word: "constant", phrase: "constant noise", meaning: "絶え間ない" },
    { id: 978, word: "periodic", phrase: "periodic reviews", meaning: "定期的な" },
    { id: 979, word: "random", phrase: "a random sample", meaning: "無作為の" },
    { id: 980, word: "arbitrary", phrase: "an arbitrary decision", meaning: "恣意的な、勝手な" },
    { id: 981, word: "adequate", phrase: "adequate salary", meaning: "十分な、まずまずの" },
    { id: 982, word: "sufficient", phrase: "sufficient evidence", meaning: "十分な" },
    { id: 983, word: "ample", phrase: "ample space", meaning: "十分な、広い" },
    { id: 984, word: "abundant", phrase: "abundant food", meaning: "豊富な" },
    { id: 985, word: "excessive", phrase: "excessive noise", meaning: "過度の" },
    { id: 986, word: "minimal", phrase: "minimal damage", meaning: "最小限の" },
    { id: 987, word: "trivial", phrase: "a trivial matter", meaning: "些細な、つまらない" },
    { id: 988, word: "crucial", phrase: "a crucial part", meaning: "決定的な、極めて重要な" },
    { id: 989, word: "vital", phrase: "vital information", meaning: "不可欠な" },
    { id: 990, word: "essential", phrase: "essential skills", meaning: "本質的な、不可欠な" },
    { id: 991, word: "ultimate", phrase: "the ultimate goal", meaning: "究極の" },
    { id: 992, word: "primary", phrase: "primary concern", meaning: "第一の、主要な" },
    { id: 993, word: "major", phrase: "a major issue", meaning: "主要な、重大な" },
    { id: 994, word: "minor", phrase: "a minor problem", meaning: "重要でない、未成年者" },
    { id: 995, word: "significant", phrase: "a significant amount", meaning: "かなりの、重要な" },
    { id: 996, word: "outstanding", phrase: "outstanding debt", meaning: "未払いの、傑出した" },
    { id: 997, word: "upcoming", phrase: "upcoming election", meaning: "今度の、来たるべき" },
    { id: 998, word: "prospective", phrase: "prospective clients", meaning: "見込みのある" },
    { id: 999, word: "potential", phrase: "potential risk", meaning: "潜在的な、可能性" },
    { id: 1000, word: "comprehensive", phrase: "a comprehensive review", meaning: "包括的な、徹底的な" }
];